import pathlib


ML_DIR = pathlib.Path("/opt/ml")
ML_PROC_DIR = ML_DIR / "processing"
PACK_LABEL = "bird_200"

TRAIN_CHANNEL = "train"
VAL_CHANNEL = "val"
TEST_CHANNEL = "test"

ML_INPUT_DIR = ML_PROC_DIR / "input"
ML_TRAIN_DIR = ML_PROC_DIR / TRAIN_CHANNEL
ML_VAL_DIR = ML_PROC_DIR / VAL_CHANNEL
ML_TEST_DIR = ML_PROC_DIR / TEST_CHANNEL

BUCKET = "sagemaker-us-east-1-180797159824"
S3_OUTPUT_OBJECT_KEY = f"s3://{BUCKET}/output"
S3_TRAIN_OBJECT_KEY = f"s3://{BUCKET}/{TRAIN_CHANNEL}"
S3_VAL_OBJECT_KEY = f"s3://{BUCKET}/{VAL_CHANNEL}"
S3_TEST_OBJECT_KEY = f"s3://{BUCKET}/{TEST_CHANNEL}"

TRAIN_REC = f"{PACK_LABEL}_{TRAIN_CHANNEL}.rec"
VAL_REC = f"{PACK_LABEL}_{VAL_CHANNEL}.rec"
TEST_REC = f"{PACK_LABEL}_{TEST_CHANNEL}.rec"

CLASS_IDS = [17, 36, 47, 68, 73]
NUM_TRAINING_SAMPLES = 209

RESIZE_SIZE = 256
